version: "3.9"

services:
    typecho:
        restart: always
        image: nginx:latest
        ports:
            - 80:80
            - 443:443
        volumes:
            - ./typecho:/data/wwwroot/typecho
            - ./nginx/typecho.conf:/etc/nginx/conf.d/default.conf
            - ./docs:/data/wwwlogs
        links:
            - php-fpm
    php-fpm:
        image: php:8.1-fpm
        volumes:
            - ./typecho:/data/wwwroot/typecho
