version: "3.9"

services:
    typecho:
        image: nginx:latest
        ports:
            - "800:80"
        volumes:
            - ./typecho:/data/wwwroot/typecho
            - ./nginx/typecho.conf:/etc/nginx/conf.d/default.conf
            - ./logs:/data/wwwlogs
        links:
            - php-fpm
    php-fpm:
        image: php:8.1-fpm
        volumes:
            - ./typecho:/data/wwwroot/typecho
